import type { Metadata } from "next";
import "./globals.css";
import NextAuthProviders from "./providers/NextAuthProciders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProviders>{children}</NextAuthProviders>
      </body>
    </html>
  );
}
